---
- name: Unregister RISC-V board
  hosts: "{{ target_node }}"
  gather_facts: no
  tasks:
    - name: Stop all running containers
      shell: |
        podman ps -q | xargs -r podman stop
      become: yes
      become_user: github-runner-user
      ignore_errors: yes
      changed_when: true

    - name: Remove all containers
      shell: |
        podman ps -a -q | xargs -r podman rm
      become: yes
      become_user: github-runner-user
      ignore_errors: yes
      changed_when: true

    - name: Remove runner image (optional)
      shell: podman rmi github-action
      become: yes
      become_user: github-runner-user
      ignore_errors: yes
      changed_when: true

    - name: Remove leftover temp directories in github-runner-user's home (optional)
      shell: |
        find /home/github-runner-user -maxdepth 1 -type d -name 'dockerbuild_*' -exec rm -rf {} +
      become: yes
      become_user: github-runner-user
      ignore_errors: yes