name: Build .NET SDK for RISC-V (latest, native)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build-sdk:
    runs-on: self-hosted
    env:
      DEBIAN_FRONTEND: noninteractive
      PACKAGESDIR: ${{ github.workspace }}/packages
      DOWNLOADDIR: ${{ github.workspace }}/downloads
      OUTPUTDIR: ${{ github.workspace }}/output
      DOTNET_ROOT: /opt/dotnet

    steps:
    - name: Install dependencies
      run: |
        whoami
        sudo apt-get update
        sudo apt-get install -y \
          git curl wget unzip tar \
          build-essential clang cmake python3 nodejs npm \
          libssl-dev libkrb5-dev pkg-config zlib1g-dev \
          llvm lttng-tools liblttng-ust-dev libelf-dev \
          libunwind-dev gettext ca-certificates gnupg
    
    - name: Get Bootstrap sdk
      run: |
        if [ ! -f /opt/dotnet/dotnet ]; then
          wget https://github.com/dkurt/dotnet_riscv/releases/download/v9.0.100/dotnet-sdk-9.0.100-linux-riscv64-gcc-ubuntu-22.04.tar.gz
          echo "Extracting SDK..."
          sudo mkdir -p /opt/dotnet
          sudo tar -xf dotnet-sdk-9.0.100-linux-riscv64-gcc-ubuntu-22.04.tar.gz -C /opt/dotnet
        else
          echo "SDK already exists at /opt/dotnet"
        fi
    - name: Add dotnet to PATH
      run: echo "/opt/dotnet" >> $GITHUB_PATH

    - name: Clone .NET SDK (main branch)
      run: |
        rm -rf sdk # In case sdk is already cloned
        git clone --depth 1 https://github.com/dotnet/sdk

    - name: Prepare build directories
      run: |
        mkdir -p ${PACKAGESDIR} ${DOWNLOADDIR} ${OUTPUTDIR}

    - name: Patch and build SDK
      run: |
        cd sdk

        # Patch build scripts to recognize riscv64 - thanks to dkurt
        sed -i 's|ppc64le|riscv64|g' Directory.Build.props || true
        sed -i "s|<clear />|<clear />\\n<add key='local' value='${PACKAGESDIR}' />|" NuGet.config || true

        ./build.sh --pack --ci -c Release --warnAsError false \
          /p:Architecture=riscv64 \
          /p:PublicBaseURL=file://${DOWNLOADDIR}/ \
          /p:DotNetBuildFromSource=true \
          /p:DOTNET_SDK_VERSION=9.0.100

        # Copy final SDK output
        cp artifacts/packages/Release/Shipping/dotnet-sdk-*-linux-riscv64.tar.gz ${OUTPUTDIR}
        cp artifacts/packages/Release/Shipping/dotnet-sdk-*-linux-riscv64.tar.gz.sha512 ${OUTPUTDIR}

    - name: Upload to GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ github.workspace }}/output/dotnet-sdk-*-linux-riscv64.tar.gz
          ${{ github.workspace }}/output/dotnet-sdk-*-linux-riscv64.tar.gz.sha512
